### PR TITLE
make forms pluggable

### PR DESCRIPTION
**Pull request by fmarco**
Hello,
how about adding this changes ?
I'd like to use custom forms in some projects, what do you think?

### CODE REVIEW

**Comment by bee-keeper** [comment]
Sorry for the late reply @fmarco - could you give me a use case for this scenario?  Thanks,

**Comment by fmarco** [comment]
@bee-keeper Hi, no problem!
A use case could be the following: i'm customizing invitations and i'd like to have a proper control on view forms and admin form to make complex customizations in parallel with invitation model.

**Comment by yakky** [comment]
@bee-keeper do you have any feedback regarding our use case and implementation?

**Comment by maxnordlund** [comment]
I also would like to customize the admin forms, so this would be a great addition. However, this PR introduces a lot of unrelated changes and lacks a nice commit message. Would you mind cleaning it up so it can be merged @fmarco?

**Comment by fmarco** [comment]
@maxnordlund Sure, i'll update this asap!

**Comment by maxnordlund** [comment]
Thank you

**Comment by fmarco** [comment]
@maxnordlund done!

**Comment by maxnordlund** [comment]
Lovely, thanks

**Comment by bee-keeper** [comment]
Ok thanks for this @fmarco - i did feel it was adding a bit of extra complexity but it's obviously useful to some people.

**Comment by maxnordlund** [comment]
Would you mind cutting a new release with this @bee-keeper? So we can start using it for real :)

**Pull request merged**
