### PR TITLE
Remove six now that Python2 is not supported

### PR DESCRIPTION
**Pull request by Siecje**
As of this commit https://github.com/bee-keeper/django-invitations/commit/3ff9f466a0d18a4bc175efba1c63af5e91a61ca9

- Python2 is no longer being tested.
- The PyPI classifiers do not include Python2

### CODE REVIEW

**Comment by FredeJ** [comment]
Any kind of outlook on when this might be merged and released? I'm in the process of upgrading to django 3 and this is the last package I'm missing, so I would be very interested in a new release :)

**Comment by FredeJ** [comment]
Also, let me know if _I_ can do anything to help this along :)

**Comment by fsecada01** [comment]
Dear @bee-keeper : 

Please accept the merge request to move `django-invitations` towards being compliant with 3.0, now that Python2 is EOL and will have a code-freeze.  If anything, a fork can be made for Python2 backward compatibility.

**Comment by bee-keeper** [comment]
Done in https://github.com/bee-keeper/django-invitations/pull/140

Thanks for contributing and sorry this didn't get merged.

**Pull request closed without merging**
