### PR TITLE
Feature/django3 support

### LINKED ISSUE #132: Django 3.0 issues
After installing Django 3rd versions the package has errors:
```
app_1  |     from .base_invitation import AbstractBaseInvitation
app_1  |   File "/app/invitations/base_invitation.py", line 3, in <module>
app_1  |     from django.utils.encoding import python_2_unicode_compatible
app_1  | ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'
```

and

```
File "/app/invitations/models.py", line 15, in <module>
app_1  |     from .adapters import get_invitations_adapter
app_1  |   File "/app/invitations/adapters.py", line 9, in <module>
app_1  |     from .utils import import_attribute
app_1  |   File "/app/invitations/utils.py", line 3, in <module>
app_1  |     from django.utils import six
app_1  | ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.7/site-packages/django/utils/__init__.py)
```

### PR DESCRIPTION
**Pull request by slei99**
closes #132

### CODE REVIEW

**Comment by slei99** [comment]
used devel as source and target. Not sure if this suits your release strategy.

**Comment by slei99** [comment]
sorry, contrib and travis newbie. I expected this to run on the source branch. I dont get why this runs on `devel` branch and not the feature branch, this is why it fails (missing space in tox. ini `r**_**requirements.txt`).
On a different note, the travis.yml looks confusing to me with the `env` and `ìnclude` config. Just tried to add a resonable test config for django 3

**Comment by Siecje** [comment]
Does `django-invitiations` support Python2? It seems like `six` can be removed entirely.

**Comment by gtwohig** [comment]
@slei99 if you change your base branch for the PR it will run against the master branch, It would also be good to test against python 3.8 now that that is out.

@bee-keeper seems sound to remove python2 support altogether (like #134 ) and also to include the Django3 testing from this PR

**Comment by MrCordeiro** [comment]
> Does `django-invitiations` support Python2? It seems like `six` can be removed entirely.

This makes total sense to me. With Python2 reaching the end of its support and Django 3 dropping the support altogether, it makes no sense to continue to support Python2 here either.

**Pull request closed without merging**
