### PR TITLE
Shownig a human-readable error when invitation is expired/accepted

### PR DESCRIPTION
**Pull request by tanzaho**
Following the discussion is issue #25 , here is a PR that shows different html files when an invitation is not anymore available.

Tests have not been run (not on my machine atm), and there is a change in adapters.py that I introduced to take into account people who are using customs allauth adapters (I am).

### CODE REVIEW

**Comment by tanzaho** [comment]
I'll look into the tests as soon as I can use my computer again.

**Comment by bee-keeper** [comment]
Thanks for this.  

I think it's along the right lines but I don't like rendering a template for expired or already accepted.  I think it's better to just use messages framework to indicate the problem and redirect to a url configured in app_settings.  This way no extra work is needed to style additional templates.  If an enduser wants a specific tpl to be used they can configure the url to point to that page and take care of that themselves.

Also, the default behaviour should be a raising a 410 meaning the user experience is almost the same as before so some level of backwards compatibility is maintained.

**Comment by bee-keeper** [comment]
Am closing this since functionality has been [merged](https://github.com/bee-keeper/django-invitations/pull/34) in another PR.  Feel free to open another issue if you feel there is something missing.  Thanks!

**Comment by tanzaho** [comment]
No problem, I implemented it on my end with the PR above and .

**Pull request closed without merging**
