### PR TITLE
Updates testing to test current versions and pass

### PR DESCRIPTION
**Pull request by gtwohig**
Version support per:
- https://devguide.python.org/#status-of-python-branches
- https://docs.djangoproject.com/en/2.2/faq/install/#what-python-version-should-i-use-with-django

Gets passing tests by marking the one failing test as requiring the database (which it does)

updates requirements.txt to current requirement version and adds tox and flake8 to requirements for local development.

### CODE REVIEW

**Comment by gtwohig** [comment]
@bee-keeper sorry for the spam as it took a few tries to get tox/travis happy on this. Hopefully this makes things a bit easier for testing going forward.

**Comment by bee-keeper** [comment]
Hi, no problem - thanks for this.  

I'd say feel free to remove Python 2.7 now as it's only a month left anyway.  I think then that if you reinstate the version dependencies everything passes?  I'm not keen on removing version numbers as then new releases might end up breaking builds.

**Comment by gtwohig** [comment]
Happy to help :smiley:

**Comment by bee-keeper** [comment]
This has been broken a shamefully long time.  Thanks again!

**Pull request merged**
