### PR TITLE
Add support for django 2.0

### PR DESCRIPTION
**Pull request by RedBeardCode**

### CODE REVIEW

**Comment by bee-keeper** [comment]
Thanks for this, I'll get master fixed up and merge it in asap.  Will endeavour to have a new release within a week.

**Comment by RedBeardCode** [comment]
Thanks. Sounds great.

**Comment by philippeluickx** [comment]
You might want to update the urls.py file as well to something like:


```
from django.urls import path

from . import views

app_name = 'invitations'
urlpatterns = [
    path('send-invite/', views.SendInvite.as_view(),
        name='send-invite'),

    path('send-json-invite/', views.SendJSONInvite.as_view(),
        name='send-json-invite'),

    path('accept-invite/<key>/', views.AcceptInvite.as_view(),
        name='accept-invite'),
]
```

**Comment by bee-keeper** [comment]
@philippeluickx happy to accept a PR on this.  Just wondering how backwards compatible it is.

**Comment by philippeluickx** [comment]
@bee-keeper fair point. It's [new in 2.0](https://docs.djangoproject.com/en/2.0/ref/urls/), so it'll give problems with django < 2.0... The old code still works.

I am not sure what the best approach is here. Check the version and have 2 giant blocks in an if-else statement?

**Comment by RedBeardCode** [comment]
Jippie it is merged. Thanks

**Comment by bee-keeper** [comment]
Thanks for headsup @philippeluickx will leave as is for now - hate if/else blocks for versions as it is.

**Pull request merged**
