### PR TITLE
Remove dependency on sites framework

### PR DESCRIPTION
**Pull request by darinsikanic**

### CODE REVIEW

**Comment by phoebebright** [comment]
+1 for this

**Comment by cromefire** [comment]
@bee-keeper Is there a specific reason why this is not merged?

**Comment by bee-keeper** [comment]
Thanks, agreed it makes sense.

**Comment by cromefire** [comment]
Do you publish this directly or will this be in some release in the future?

**Comment by jws** [comment]
@bee-keeper can you publish this release?

**Pull request merged**
