### PR TITLE
JazzBand project guidelines

### LINKED ISSUE #165: Transfer project ownership to Jazzband?
The [Jazzband organization](https://jazzband.co/) actively maintains several [Django projects](https://jazzband.co/projects), many of which are in wide use. Jazzband has tools and a process in place for project governance, to encourage sustainability of projects.

Would you consider transferring the ownership of this project to the Jazzband organization in order to encourage the sustained development of django-invitations?

### PR DESCRIPTION
**Pull request by brylie**
Closes #165 

Adding a few elements to adhere to JazzBand project guidelines.

### CODE REVIEW

**Comment by igorpejic** [comment]
@brylie Why is this a Draft still?

It could happen that the draft status makes the owner more reluctant to merge it.

Django 4.0 will soon be released and merging MRs like https://github.com/bee-keeper/django-invitations/pull/144 will be more than welcome by the community.

**Comment by brylie** [comment]
I converted the PR to ready for review.

**Review by jayvdb — APPROVED** [review]

**Comment by MrCordeiro** [comment]
What is the status of this transfer? Any news?

**Comment by brylie** [comment]
@MrCordeiro, your changes are now included in this pull request.

**Comment by brylie** [comment]
@bee-keeper, we have the green light to transfer this project to the Jazzband organization. Would you please consider merging this pull request and initiating the transfer?

https://github.com/jazzband/help/issues/237#issuecomment-1023298613

**Pull request merged**
